resolver: lts-17.10 # Use an appropriate resolver version based on your needs

packages:
  - .

allow-newer: true

build:
  library-profiling: true
  executable-profiling: true

extra-deps:
  - random-1.2.1
  - parallel-3.2.2.0
  - hs-carbon-0.1.1.0
  - deepseq-1.4.6.1
  - containers-0.7
  - bytestring-0.10.12.1
  - async-2.2.4
  - time-1.12.2
  - text-1.2.5.0
  - binary-0.8.9.1
  # - repa-3.4.1.5
  # - repa-algorithms-3.4.0.2
  # - accelerate-1.3.0.0
  # - monad-par-0.3.4
